title: >-
  Shoe Cleaner Kit - ShoeAnew - all Natural, 8 Ounces, Brush and Cloth for Cleaning Sneakers, Tennis shoes, Canvas, Plastic, Mesh, Knit and More
email: help@shoeanew.com
description: >- # this means to ignore newlines until "baseurl:"
  Life gets messy! Don’t worry! Our shoe cleaner concentrate is ready to help clean up the aftermath and leave your shoes looking like they are fresh out of the box. Though other products may remove dirt and debris, ours goes beyond that and disinfects the surface, meaning your footwear will be as clean as can be, killing 99.9 percent of germs. The spray-top makes lathering a simple task, while the brush, cloth, and cleaner work in harmony to achieve cleaner, brighter and newer looking footwear! Just apply a small amount of our shoe cleaner concentrate, scrub grime away with our wood brush, and wipe clean with our microfiber cloth. Try it on your feet to eliminate foot odor or spray it in your shoes as a shoe odor eliminator! Our cleaner is completely safe for the environment, as well as non-toxic. This means you can clean your shoes without any harmful effects to you or your surroundings. Get one yourself or grab one for a friend. Our shoe cleaner concentrate is the perfect gift for your friends and family. Click the "Add to Cart" Button above and keep your shoes clean and smelling fresh today!
baseurl: "" # the subpath of your site if applicable, e.g. /blog
url: "https://www.shoeanew.com" # the base hostname & protocol for your site, e.g. https://example.com
order_cta: https://www.amazon.com/Shoe-Cleaner-Kit-ShoeAnew-Microfiber/dp/B01F9FVUEA

# Permalink format (/blog/ is ignored for pages)
permalink: /:title

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# set some common post defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name
  - scope:
      path: "" # an empty string here means all files in the project
      type: "solutions" # previously `post` in Jekyll 2.2.
    values:
      image: "assets/img/uploads/screenshot-editor.jpg"

collections:
  slides:
    output: false
    sort_by: order

# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

# Include in processing (e.g. Netlify directives)
# Uncomment before use

include:
  - _redirects
  - .netlify

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
